Updated plumbing commands to support new repo structure

diff --git a/snappify-alias b/snappify-alias
--- a/snappify-alias
+++ b/snappify-alias
@@ -1,67 +1,53 @@
 #!/bin/bash
 #
 # snappify snapshot management suite
-# http://bueller.ca/software/snappify
+# github.com/mattferris/snappify
 #
-# Copyright (c) 2013 Matt Ferris
+# Copyright (c) 2018 Matt Ferris
 # Released under the BSD 2-clause license
-# http://bueller.ca/software/snappify/license
+# github.com/mattferris/snappify/blob/master/LICENSE.txt
 
-# usage: snappify-alias repo alias snap
+# the location of the snap repo
+root=".snappify"
 
-me=`basename "$0"`
-repo=$1
-snapalias=$2
-snap=$3
+# update the location of the snap repo if it was included in the environment
+if [ ! -z "$SNAPPIFY_ROOT" ]; then
+    root=$SNAPPIFY_ROOT
+fi
 
-_usage() {
-    echo "usage: $me repo [ alias [ snap ] ]"
+# report an error
+function err {
+    echo "error: $2" >&2
+    exit $1
 }
 
-if [ -z $repo ]; then
-    _usage
-    exit 1
-fi
+# report a notice
+function notice {
+    echo "notice: $1" >&2
+}
 
-if [ ! -d "$repo" ]; then
-    echo error: repository doesn\'t exist, \"$repo\"
-    exit 1
-fi
+# collect arguments
+alias=$1
+hash=$2
 
-if [ ! -d "$repo/aliases" ]; then
-    echo error: bad repository, \"$repo/aliases\" doesn\'t exist
-    exit 1
-fi
-
-if [ ! -d "$repo/snaps" ]; then
-    echo error: bad repository, \"$repo/snaps\" doesn\'t exist
-    exit 1
-fi
-
-if [ -z $snapalias ]; then
-    for i in `ls -1 "$repo/aliases"`; do
-        echo $i '->' `cat "$repo/aliases/$i"`
-    done
-else
-    if [ -z $snap ]; then
-        if [ -f "$repo/aliases/$snapalias" ]; then
-            cat "$repo/aliases/$snapalias"
-        else
-            aliaslen=${#snapalias}
-            for i in `ls -c1 "$repo/snaps"`; do
-                if [ "${i:0:$aliaslen}" = "$snapalias" ]; then
-                    echo $i
-                    break
-                fi
-            done
-        fi
-    elif [ "$snap" = "-" ]; then
-        if [ -f "$repo/aliases/$snapalias" ]; then
-            rm "$repo/aliases/$snapalias"
-            echo removed alias $snapalias
-        fi
-    else
-        echo $snap > "$repo/aliases/$snapalias"
-        echo $snapalias '->' $snap
+if [ -z "$alias" ]; then
+    if [ -d "$root/aliases" ]; then
+        for i in $(ls -1 "$root/aliases"); do
+            echo "$i -> $(cat "$root/aliases/$i")"
+        done
     fi
+elif [ -z "$hash" ]; then
+    if [ -f "$root/aliases/$alias" ]; then
+        cat "$root/aliases/$alias"
+    else
+        err 2 "alias undefined"
+    fi
+elif [ ! -z "$hash" ]; then
+    if [ ! -d "$root/aliases" ]; then
+        mkdir "$root/aliases" || err 2 "failed to create aliases directory"
+    fi
+    echo "$hash" > "$root/aliases/$alias"
+else
+    echo "usage: $(basename $0) [ <alias> [ <hash> ] ]" >&2
+    exit 1
 fi
diff --git a/snappify-restore b/snappify-restore
--- a/snappify-restore
+++ b/snappify-restore
@@ -1,62 +1,43 @@
 #!/bin/bash
 #
 # snappify snapshot management suite
-# http://bueller.ca/software/snappify
+# github.com/mattferris/snappify
 #
-# Copyright (c) 2013 Matt Ferris
+# Copyright (c) 2018 Matt Ferris
 # Released under the BSD 2-clause license
-# http://bueller.ca/software/snappify/license
+# github.com/mattferris/snappify/blob/master/LICENSE.txt
 
-# usage: snappify-restore repo snap [ file ]
+# the location of the snap repo
+root=".snappify"
 
-repo=$1
-snap=$2
-file=$3
-me=`basename "$0"`
+# update the location of the snap repo if it was included in the environment
+if [ ! -z "$SNAPPIFY_ROOT" ]; then
+    root=$SNAPPIFY_ROOT
+fi
 
-if [ -z $repo -o -z $snap ]; then
-    echo usage: $me repo snap [ file ]
+# report an error
+function err {
+    echo "error: $2" >&2
+    exit $1
+}
+
+# report a notice
+function notice {
+    echo "notice: $1" >&2
+}
+
+# determine relative path length
+realbase=$(dirname $(realpath "$root"))
+baselen=$(echo -n "$realbase/ " | wc -c)
+
+# collect arguments
+hash=$1
+path=$2
+
+# make sure we have everything we need
+if [ -z "$hash" ]; then
+    echo "usage: $(basename $0) <hash> [ <path> ... ]"
     exit 1
 fi
 
-if [ ! -d "$repo" ]; then
-    echo error: repository doesn\'t exist, \"$repo\"
-    exit 1
-fi
 
-if [ ! -d "$repo/snaps" ]; then
-    echo error: bad repository, \"$repo/snaps\" doesn\'t exist
-    exit 1
-fi
-
-if [ ! -d "$repo/meta" ]; then
-    echo error: bad repository, \"$repo/meta\" doesn\'t exist
-    exit 1
-fi
-
-ifalias=`snappify-alias "$repo" "$snap"`
-if [ ! "$ifalias" = "" ]; then
-    snap=$ifalias
-fi
-
-if [ ! -d "$repo/snaps/$snap" ]; then
-    echo error: snap doesn\'t exist
-    exit 1
-fi
-
-if [ ! -f "$repo/meta/$snap" ]; then
-    echo error: can\'t find metadata for snap, \"$snap\"
-    exit 1
-fi
-
-path=`cat "$repo/meta/$snap"`
-
-if [ ! -d "$path" ]; then
-    echo error: snap path doesn\'t exist, \"$path\"
-    exit 1
-fi
-
-#rm -r "$path/"*
-rsync -aq --delete "$repo/snaps/$snap/"* "$path/"
-
-echo restored $snap into $path
diff --git a/snappify-snap b/snappify-snap
--- a/snappify-snap
+++ b/snappify-snap
@@ -1,63 +1,97 @@
 #!/bin/bash
 #
 # snappify snapshot management suite
-# http://bueller.ca/software/snappify
+# github.com/mattferris/snappify
 #
-# Copyright (c) 2013 Matt Ferris
+# Copyright (c) 2018 Matt Ferris
 # Released under the BSD 2-clause license
-# http://bueller.ca/software/snappify/license
+# github.com/mattferris/snappify/blob/master/LICENSE.txt
 
-# usage: snappify-snap repo [ target ]
+# the location of the snap repo
+root=".snappify"
 
-repo=$1
-target=`pwd`
-snap_alias=$3
-me=`basename "$0"`
-
-if [ -z $1 ]; then
-    echo usage: $me repo [ target ]
-    exit 1
+# update the location of the snap repo if it was included in the environment
+if [ ! -z "$SNAPPIFY_ROOT" ]; then
+    root=$SNAPPIFY_ROOT
 fi
 
-if [ ! -z $2 ]; then
-    target=$2
+# report an error
+function err {
+    echo "error: $2" >&2
+    exit $1
+}
+
+# report a notice
+function notice {
+    echo "notice: $1" >&2
+}
+
+# generate a checksum for a string
+function strsum {
+    echo -n "$1" | sha1sum | cut -d\  -f1
+}
+
+# search current and parent directories for repo
+function findrepo {
+    path=$1
+    if [ -d "$path/.snappify" ]; then
+        echo "$path/.snappify"
+        return 0
+    elif [ "$path" = "/" ]; then
+        err 2 "no repository found"
+    else
+        findrepo "$(dirname $path)"
+    fi
+}
+
+# collect arguments
+message=$1
+
+# determine the location of the repo
+if [ ! -d "$root" ]; then
+    root=$(findrepo $(pwd))
 fi
 
-if [ ! -d "$repo" ]; then
-    echo error: repository doesn\'t exist \"$repo\"
-    exit 1
+# write the files to the repo
+hash=$(SNAPPIFY_ROOT="$root" snappify-write "$(dirname "$root")")
+
+# verify write was successful
+if [ ! $? = 0 ]; then
+    err 2 "snapshot failed, an error was encountered while writing to $root"
 fi
 
-if [ ! -d "$repo/snaps" ]; then
-    echo error: bad repository, \"$repo/snaps\" doesn\'t exist
-    exit 1
+# make sure snaps directory exists
+if [ ! -d "$root/snaps" ]; then
+    mkdir "$root/snaps" || err 2 "failed to create snap directory"
 fi
 
-if [ ! -d "$repo/meta" ]; then
-    echo error: bad repository, \"$repo/meta\" doesn\'t exist
-    exit 1
+# check if this fileset is the same as the last snapshot
+last=$(snappify-alias last 2>/dev/null)
+if [ $? = 0 -a ! -z "$last" ]; then
+    lasthash=$(snappify-read snap "$last" | head -n1 | awk -F'  ' '{print $3}')
+    if [ "$hash" = "$lasthash" ]; then
+        err 2 "no changes since last snapshot, aborting"
+    fi
 fi
 
-if [ ! -d "$target" ]; then
-    echo error: target doesn\'t exist, \"$target\"
-    exit 1
+data="$(whoami)  $(date -R)  $hash"
+snapsum=$(strsum "$data")
+
+# write snapshot metadata
+cat <<EOF > "$root/snaps/$snapsum"
+$data
+$message
+EOF
+
+# verify snap was written
+if [ ! $? = 0 ]; then
+    err 2 "snapshot failed, failed to write snapshot metadata"
 fi
 
-snap=`dd if=/dev/urandom bs=1024 count=1 2>&1 | sha1sum | awk '{print \$1}'`
-snapdir="$repo/snaps/$snap"
-mkdir "$snapdir"
-if [ ! -z "$snap_alias" ]; then
-    snappify-alias "$repo" "$snap_alias" $snap > /dev/null 2>&1
-fi
+# add snapshot to log
+echo "$snapsum" >> "$root/log"
 
-exclude=""
-if [ -f "$repo/conf/ignore" ]; then
-    exclude="--exclude-from='$repo/conf/ignore'"
-fi
+# point 'last' alias to new snapshot
+snappify-alias last "$snapsum" || err 2 "failed to updated 'last' alias to point to new snap"
 
-rsync -aq --exclude=".snappify" $exclude "$target/"* "$snapdir/" #> /dev/null 2>&1
-
-echo "$target" > "$repo/meta/$snap"
-
-echo $snap
-
+echo "created snapshot $snapsum"
